project:
  name: quickstart-ibm-mq-eks
  package_lambda: false
  shorten_stack_name: true
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  s3_bucket: ''
tests:
  mq-eks:
    template: ./templates/ibm-mq-main.template.yaml
    parameters:
      EKSClusterName: was-cluster-$[taskcat_random-string]
      SetupNewECR: "Yes"
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: $[taskcat_project_name]/
      AvailabilityZones: $[taskcat_genaz_3]
      MQAppPassword: $[taskcat_genpass_10]
      MQAdminPassword: $[taskcat_genpass_10]
    regions:
      - eu-west-1
      - eu-west-2
      - eu-west-3