---
# © Copyright IBM Corporation 2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: This master template creates a VPC infrastructure for a multi-AZ, multi-tier
  deployment of IBM MQ 9.0.3 on AWS EC2, with EFS. It deploys a VPC with bastions
  and the IBM MQ solution. The IBM MQ solution is configured to use an EFS for persistant
  storage of the MQ volume. **WARNING** This template creates EC2 instances and related
  resources. You will be billed for the AWS resources used if you create a stack from
  this template. IBM MQ is licensed seperatley, please review the terms and conditions
  here (http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?la_formnum=Z125-3301-14&li_formnum=L-APIG-AKHJ8V)
  for further details. (qs-1nhqnkuin)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Software License Agreement
      Parameters:
      - LicenseAgreement
    - Label:
        default: VPC & Bastion Configuration
      Parameters:
      - AvailabilityZones
      - AdminRemoteAccessCIDR
      - AdminConsoleAccessCIDR
      - ClientAppAccessCIDR
      - KeyPairName
      - BastionAMIOS
      - BastionInstanceType
    - Label:
        default: IBM MQ Instance Configuration
      Parameters:
      - MQOwner
      - MQInstanceName
      - MQInstanceType
      - QueueManagerName
      - MQConsoleUsername
      - MQConsolePassword
      - MQAdminPassword
      - MQAppPassword
    - Label:
        default: IBM MQ License
      Parameters:
      - LicenseS3Bucket
      - LicenseS3KeyPrefix
    - Label:
        default: AWS Quick Start Configuration
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
    ParameterLabels:
      AdminConsoleAccessCIDR:
        default: Allowed Admin Web Console External Access CIDR
      AdminRemoteAccessCIDR:
        default: Allowed Bastion External Access CIDR
      AvailabilityZones:
        default: Availability Zones
      BastionAMIOS:
        default: Bastion AMI Operating System
      BastionInstanceType:
        default: Bastion Instance Type
      ClientAppAccessCIDR:
        default: Allowed Client Application External Access CIDR
      MQInstanceName:
        default: IBM MQ Instance Name
      MQInstanceType:
        default: IBM MQ Instance Type
      KeyPairName:
        default: Key Pair Name
      LicenseAgreement:
        default: License Agreement
      LicenseS3Bucket:
        default: IBM MQ License S3 Bucket Name
      LicenseS3KeyPrefix:
        default: IBM MQ License S3 Key Prefix Name
      MQConsoleUsername:
        default: IBM MQ Web Console Admin Username
      MQConsolePassword:
        default: IBM MQ Web Console Admin Password
      MQAdminPassword:
        default: mqadmin Password
      MQAppPassword:
        default: mqapp Password
      MQOwner:
        default: IBM MQ Instance Owner
      QueueManagerName:
        default: Queue Manager Name
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
Parameters:
  AdminRemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the IBM MQ server via
      the Bastion Server. We recommend that you set this value to a trusted IP range.
    Type: String
  AdminConsoleAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the IBM MQ Web Console
      via the ELB. We recommend that you set this value to a trusted IP range.
    Type: String
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. Only
      two Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  BastionAMIOS:
    AllowedValues:
    - Amazon-Linux-HVM
    - CentOS-7-HVM
    - Ubuntu-Server-14.04-LTS-HVM
    - Ubuntu-Server-16.04-LTS-HVM
    Default: Amazon-Linux-HVM
    Description: The Linux distribution for the AMI to be used for the bastion instances
    Type: String
  BastionInstanceType:
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for the bastion instances
    Type: String
  ClientAppAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to allow access for IBM MQ Client
      Applications. We recommend that you set this value to a trusted IP range.
    Type: String
  MQInstanceType:
    Description: IBM MQ server EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - c1.medium
    - c1.xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - g2.2xlarge
    - g2.8xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - hi1.4xlarge
    - hs1.8xlarge
    - cr1.8xlarge
    - cc2.8xlarge
    - cg1.4xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  QueueManagerName:
    Description: Name to use for the IBM MQ queue manager. Queue Manager name can include Uppercase Letters, Numbers,
      periods (.), underscores (_), and percentage (%) (Max Length of 48 Characters).
    Type: String
    AllowedPattern: ^[0-9A-Z._%]+([0-9A-Z._\/%]*[0-9A-Z.%])*$
    MaxLength: 48
    Default: QM1
    ConstraintDescription: must be a valid MQ queue manager name.
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  LicenseAgreement:
    Description: I have read and agree to the license terms for IBM MQ (http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?la_formnum=Z125-3301-14&li_formnum=L-APIG-AKHJ8V).
    Type: String
    Default: '-'
    AllowedValues:
    - I agree
    - '-'
    ConstraintDescription: must answer 'I agree'
  LicenseS3Bucket:
    AllowedPattern: ^[0-9a-zA-Z]?([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: S3 bucket name can include numbers, lowercase letters,
      uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name where you store your IBM MQ License file. Leave blank
      to use 90 day Trial license.
    Type: String
    MinLength: 0
  LicenseS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z]?([0-9a-zA-Z-/]*[0-9a-zA-Z])*$
    ConstraintDescription: S3 key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/). It cannot start or end with a hyphen
      (-) or (/).
    Description: S3 key prefix for the directory your IBM MQ License file is stored.
      Leave blank to use 90 day Trial license.
    Type: String
    MinLength: 0
  MQConsoleUsername:
    Description: Admin Username used for accessing Web Console and REST Api
    Default: mqconsoleadmin
    Type: String
  MQConsolePassword:
    Description: Admin Password to access the MQ Web Console (Min. Length of 8 Characters, Max Length of 12 Characters)
    Type: String
    MinLength: 8
    MaxLength: 12
    NoEcho: true
  MQAdminPassword:
    Description: Password for predefined mqadmin user used to administer MQ (Min.
      Length of 8 Characters, Max Length of 12 Characters)
    Type: String
    MinLength: 8
    MaxLength: 12
    NoEcho: true
  MQAppPassword:
    Description: Password for predefined mqapp user used by applications to securely
      connect to MQ (Min. Length of 8 Characters, Max Length of 12 Characters)
    Type: String
    MinLength: 8
    MaxLength: 12
    NoEcho: true
  MQInstanceName:
    Description: Name for the IBM MQ instance that is deployed to EC2
    Type: String
    Default: ibm-mq
  MQOwner:
    Description: Set Owner tag for the IBM MQ instance
    Default: ibm-mq
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-ibm-mq/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
Rules:
  LicenseAgreementRule:
    Assertions:
    - Assert:
        Fn::Contains:
        - - I agree
        - Ref: LicenseAgreement
      AssertDescription: User must agree to the terms of the license agreement.
  EFSSupportedRegionRule:
    Assertions:
    - Assert:
        Fn::Contains:
        - - us-east-1
          - us-east-2
          - us-west-2
          - eu-west-1
          - ap-southeast-2
        - !Ref AWS::Region
      AssertDescription: This Quick Start utilizes Amazon EFS which is only available
        in the US East (N. Virginia), US East (Ohio), US West (Oregon), EU (Ireland)
        and Asia Pacific (Sydney) regions. Please launch the stack in one of these
        regions to continue.
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
      Parameters:
        AvailabilityZones:
          Fn::Join:
          - ','
          - Ref: AvailabilityZones
        KeyPairName:
          Ref: KeyPairName
        NumberOfAZs: '2'
  BastionStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template
      Parameters:
        BastionAMIOS:
          Ref: BastionAMIOS
        BastionInstanceType:
          Ref: BastionInstanceType
        EnableBanner: true
        KeyPairName:
          Ref: KeyPairName
        PublicSubnet1ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1ID
        PublicSubnet2ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2ID
        QSS3BucketName:
          Ref: QSS3BucketName
        QSS3KeyPrefix:
          Fn::Sub: ${QSS3KeyPrefix}submodules/quickstart-linux-bastion/
        RemoteAccessCIDR:
          Ref: AdminRemoteAccessCIDR
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
  MQStack:
    DependsOn: BastionStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/ibm-mq.template
      Parameters:
        AdminConsoleAccessCIDR:
          Ref: AdminConsoleAccessCIDR
        BastionSecurityGroupID:
          Fn::GetAtt:
          - BastionStack
          - Outputs.BastionSecurityGroupID
        ClientAppAccessCIDR:
          Ref: ClientAppAccessCIDR
        KeyPairName:
          Ref: KeyPairName
        LicenseAgreement:
          Ref: LicenseAgreement
        LicenseS3Bucket:
          Ref: LicenseS3Bucket
        LicenseS3KeyPrefix:
          Ref: LicenseS3KeyPrefix
        MQConsoleUsername:
          Ref: MQConsoleUsername
        MQConsolePassword:
          Ref: MQConsolePassword
        MQAdminPassword:
          Ref: MQAdminPassword
        MQAppPassword:
          Ref: MQAppPassword
        MQOwner:
          Ref: MQOwner
        MQInstanceName:
          Ref: MQInstanceName
        MQInstanceType:
          Ref: MQInstanceType
        PrivateSubnet1ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1AID
        PrivateSubnet2ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2AID
        PublicSubnet1ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1ID
        PublicSubnet2ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2ID
        QueueManagerName:
          Ref: QueueManagerName
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
Outputs:
  MQRestApiURL:
    Description: URL for Elastic Load Balancer to connect to REST API
    Value: !GetAtt MQStack.Outputs.MQRestApiURL
  MQConsoleURL:
    Description: URL for Elastic Load Balancer to connect to MQ Console
    Value: !GetAtt MQStack.Outputs.MQConsoleURL
  ReadMeInfo:
    Description: 'For more information and details visit:'
    Value: https://aws.amazon.com/quickstart/architecture/ibm-mq/
...
